src/UserBundle/Form/RegistrationType.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace UserBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Validator\Constraints\NotBlank;

class RegistrationType extends AbstractType {

    public function buildForm(FormBuilderInterface $builder, array $options) {
        $builder
                ->add('agree', CheckboxType::class, [
                    'mapped' => false,
                    'label' => 'agree_use',
                    'constraints' => [
                        new NotBlank(array(
                                ))
                    ]
                ])
        ;
    }

    public function getParent() {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';

        // Or for Symfony < 2.8
        // return 'fos_user_registration';
    }

    public function getBlockPrefix() {
        return 'app_user_registration';
    }

    // For Symfony 2.x
    public function getName() {
        return $this->getBlockPrefix();
    }

}

src/UserBundle/Resources/views/Group/edit.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:edit_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Group/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

{{ form_start(form, { 'action': path('fos_user_group_edit', {'groupName': group_name}), 'attr': { 'class': 'fos_user_group_edit' } }) }}
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'group.edit.submit'|trans }}" />
    </div>
{{ form_end(form) }}

src/UserBundle/Resources/views/Group/list.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:list_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Group/list_content.html.twig
<div class="fos_user_group_list">
    <ul>
    {% for group in groups %}
        <li><a href="{{ path('fos_user_group_show', {'groupName': group.getName()} ) }}">{{ group.getName() }}</a></li>
    {% endfor %}
    </ul>
</div>

src/UserBundle/Resources/views/Group/new.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:new_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Group/new_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

{{ form_start(form, { 'action': path('fos_user_group_new'), 'attr': { 'class': 'fos_user_group_new' } }) }}
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'group.new.submit'|trans }}" />
    </div>
{{ form_end(form) }}

src/UserBundle/Resources/views/Group/show.html.twig
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
{% include "FOSUserBundle:Group:show_content.html.twig" %}
{% endblock fos_user_content %}

src/UserBundle/Resources/views/Group/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="fos_user_group_show">
    <p>{{ 'group.show.name'|trans }}: {{ group.getName() }}</p>
</div>